# Generated by Django 5.0.4 on 2024-04-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Начало рассылки')),
                ('end_date', models.DateTimeField(verbose_name='Окончание рассылки')),
                ('interval', models.PositiveSmallIntegerField(choices=[(1, 'DAILY'), (2, 'WEEKLY'), (3, 'MONTHLY'), (4, 'ONCE')], null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'CREATED'), (2, 'COMPLETED'), (3, 'LAUNCHED'), (4, 'FAILED'), (5, 'SUSPENDED')], null=True)),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус последний попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
